language: node_js
node_js:
- '4'
branches:
  only:
  - dev
env:
  global:
  - secure: GtkK1YzypRm/+PdQn7yBk3eMreKc7Vo5UEBEIoYC2H2w7q7o6+aIsS647tbOfbPDU2qn+KBecY84IYXOLBAxshj5+Kj4bUvDdmQu04VdT98wHmw7KRqVt2fLa+JU20ifJ92f1NU/TsJjcL913EbI9B/YIfgx/Fn5G/zY4yyk0oFniIZIr3u3GTD8KmqVSCME01sNumDOO7gBQOH9LS8Ju3x0HNJMkTOhHHP4y6hOHFzDTSZKkaEoSeSIS4uokDXM3YBvTz96wwP2X2huvoKuWEIUs6EJ1BOZUpzGKy5Gx83YDsJUULuOXNFMTDEd54TA7M4lVN2TqOwVKR67+wLmpvEKs58EuhrFHet23N4zcOjlKl56n25/c2acZ4Vhp8azX900VPkkbI3knMPpFiS64AMSICWXWu16uBajZFFp1tAVOQNupfKVfJ58zhNxaeSo6r0rXCO7buQNhwnE6e3okpxs0Q6oGGCOlx4BDcSw1IydAKSDvizTfMtpSW4YVi2cTEu6cG3KlXIvWUsxPpYI1iKytdOOopcSrl00lHGmbxG1geM3/Vg8p//QAVmceVlcjCegT5xkHzGSW7uLQHnivuGhskKX0XNEi80klAwVkrQ4c0bXfykBbK1qTVisNprjONWRlg+sBBoZijPifrvVjaXsZ3rWkOGljsUyOuiGw5k=
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Nanmen"
- git config --global user.email "ningfan210@126.com"
- sed -i'' "s~git@github.com:Nanmen/Nanmen.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/Nanmen/Nanmen.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
