language: node_js
node_js:
- "4"  # nodejs的版本
branches:
  only:
  - dev  # 设置自动化部署的源码分支

# ------------------------------------------------
# 下面是你的Token加密信息，不要替换
# ------------------------------------------------
env:
  global:
    secure: ak9WwhkHybgQSJy7AFblpQAJdGiRAlqYj9HLz0AaOYfH2PyaU4wPEXGHfdoeXhveFJe8Kug4aHnm6scFLDmh/Pf5TRmMCLBe2yyt2UfzdfIL8xqadGzFJ2EYGMQKidnnGHAcpNejdm9nNpftIJPOls28JQvnqwH6SQ/ql+Ib6sdNRae+XT2sD3E4MFohqNO4wShLT5eJBbVE8uUhvhgwPkUQwKEC/Y5rU684YlDjyjb6W+yDw4rHAK/qi1B1IkUGysTEmBtsIxHc66IVfDZ5PDm/zVwklQRFqkAdE+z6w0MQKSX40rL4R5fhwXvB3oX3fglINP2/gXDD6jl2/VM7asQbjp3FPXllOVsaPJg9edziXFBC7jLgj03/aYeCr/iyjJCjVCaO2KBcOQYJiD4j0rd+RW0y9brGiCSvcK1TaHN85vGHq2yuyqUtUgiTswz/vTeHpqrpZPdn7siAsbxPthbWSCmxj3usH/dDr6AFXYuY0Zd9oeIMdFYHU0vdRJcmFJyr2fbElUZAzFfwBUYjS4xRNLgRfzyfGAEgMGTt909b2z2GnsyFzptRSZL6hlum6ysqGq56VwUG6ynS1Ecb9EG3f+vvKgubkj+sbo5o9Zh4PEyXfM2jz0fPF+jUiu6Q7b07iDuploKr6fTdLhxr4J3w0nRNAoMpqRUxJ8jIShM=
before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "Nanmen"
- git config --global user.email ningfan210@126.com 
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~git@github.com:Nanmen/Nanmen.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/Nanmen/Nanmen.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy