language: node_js
node_js:
- '4'
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/Nanmen/Nanmen.github.io.git
  - secure: m96FPXcXRnT913kQNL9N3MU9EKBVJinR2RsdV8u3Z7txFd+1XzGUz5ZlStlaQ83G+fjK2tOjo56CAIMQdW81KSVvEShl2qSfQs2bxeFgMx7QA0oIlA8r61VknSE612daVu+RsaTPZ/6VVdd2ZfQ/SUXps1vkU5hSJY5Xd7GIMUW9OYta0AJXuMKdym8T8IAUKEsFRe97xS+rjfjG+KgnIYQAaQKzpsDyFeu9Srnvh+Z8OW9kX2ApyoJ5WD3YjdHhyJ3DFXg2x0iCO2eabwSujFR2AllaiNku43zhp3lJK1IqW9w7dCTuprpea5ZAnDlNgtPTdUmAfZHZ2WegegDhbZCoYzP6OPGYMD/YKwOaClrA3UNQo94bmhzzPqa/W3Oxj85yKHGhgSDb5KEzPpZtl+3WbXqSwwyg9gPKU8qrig7aFKr6oQvDhLMX7uIC05xzjcsbgfFTjzvyDVVoksbEeC6pY/PmSq86UCdqD9lauMFV7AE1J/7RpXb/X8W7ECZTURVIYl07UguON9aFEaAmJQvo0rwFVZLaNGI+iI0VfT4pkcDmyTH2pjLfgXPK29RYmLto2NGuTYikKTcSaYZQFSaQ6aOFmDOUmpjQr9F5jemU543Adq9JS0j2qXECSH0tVPFtQ8G2uZBSJlh1YRJdW4MSvG/epVSJqx3lOXPLEr0=
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Nanmen"
- git config --global user.email "ningfan210@126.com"
- sed -i'' "s~git@github.com:Nanmen/Nanmen.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/Nanmen/Nanmen.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
